var listWords = [
    { "english": "a", "russian": "любой, один, каждый, некий", "section": 2, "subsection": 0 },
    { "english": "able", "russian": "способный, быть в состоянии", "section": 3, "subsection": 1 },
    { "english": "about", "russian": "о", "section": 2, "subsection": 0 },
    { "english": "account", "russian": "счет, считать", "section": 1, "subsection": 2 },
    { "english": "acid", "russian": "кислота, кислый", "section": 3, "subsection": 1 },
    { "english": "across", "russian": "через", "section": 2, "subsection": 0 },
    { "english": "act", "russian": "действия", "section": 1, "subsection": 2 },
    { "english": "addition", "russian": "дополнение", "section": 1, "subsection": 2 },
    { "english": "adjustment", "russian": "регулировка, установка", "section": 1, "subsection": 2 },
    { "english": "advertisement", "russian": "реклама", "section": 1, "subsection": 2 },
    { "english": "after", "russian": "после", "section": 2, "subsection": 0 },
    { "english": "again", "russian": "снова", "section": 2, "subsection": 0 },
    { "english": "against", "russian": "против", "section": 2, "subsection": 0 },
    { "english": "agreement", "russian": "соглашение", "section": 1, "subsection": 2 },
    { "english": "air", "russian": "воздух, проветривать", "section": 1, "subsection": 2 },
    { "english": "all", "russian": "все, весь", "section": 2, "subsection": 0 },
    { "english": "almost", "russian": "почти", "section": 2, "subsection": 0 },
    { "english": "among", "russian": "среди", "section": 2, "subsection": 0 },
    { "english": "amount", "russian": "количество, означать, составлять", "section": 1, "subsection": 2 },
    { "english": "amusement", "russian": "развлечение", "section": 1, "subsection": 2 },
    { "english": "and", "russian": "и", "section": 2, "subsection": 0 },
    { "english": "angle", "russian": "угол, поворачивать", "section": 1, "subsection": 1 },
    { "english": "angry", "russian": "сердитый", "section": 3, "subsection": 1 },
    { "english": "animal", "russian": "животное", "section": 1, "subsection": 2 },
    { "english": "answer", "russian": "ответ, отвечать", "section": 1, "subsection": 2 },
    { "english": "ant", "russian": "муравей", "section": 1, "subsection": 1 },
    { "english": "any", "russian": "любой, никто", "section": 2, "subsection": 0 },
    { "english": "apparatus", "russian": "аппарат", "section": 1, "subsection": 2 },
    { "english": "apple", "russian": "яблоко", "section": 1, "subsection": 1 },
    { "english": "approval", "russian": "одобрение", "section": 1, "subsection": 2 },
    { "english": "arch", "russian": "арка, дуга, выгибать", "section": 1, "subsection": 1 },
    { "english": "argument", "russian": "спор, аргумент", "section": 1, "subsection": 2 },
    { "english": "arm", "russian": "рука, вооружать", "section": 1, "subsection": 1 },
    { "english": "army", "russian": "армия", "section": 1, "subsection": 1 },
    { "english": "art", "russian": "искусство, художественный", "section": 1, "subsection": 2 },
    { "english": "as", "russian": "поскольку, как", "section": 2, "subsection": 0 },
    { "english": "at", "russian": "в", "section": 2, "subsection": 0 },
    { "english": "attack", "russian": "нападение, нападать", "section": 1, "subsection": 2 },
    { "english": "attempt", "russian": "попытка, пытаться", "section": 1, "subsection": 2 },
    { "english": "attention", "russian": "внимание", "section": 1, "subsection": 2 },
    { "english": "attraction", "russian": "достопримечательности", "section": 1, "subsection": 2 },
    { "english": "authority", "russian": "власть, полномочие", "section": 1, "subsection": 2 },
    { "english": "automatic", "russian": "автоматический", "section": 3, "subsection": 1 },
    { "english": "awake", "russian": "активный, пробуждать, просыпаться", "section": 3, "subsection": 2 },
    { "english": "baby", "russian": "ребёнок, младенец", "section": 1, "subsection": 1 },
    { "english": "back", "russian": "назад, спина, отступать", "section": 1, "subsection": 2 },
    { "english": "bad", "russian": "плохой", "section": 3, "subsection": 2 },
    { "english": "bag", "russian": "сумка", "section": 1, "subsection": 1 },
    { "english": "balance", "russian": "баланс, уравновешивать", "section": 1, "subsection": 2 },
    { "english": "ball", "russian": "мяч", "section": 1, "subsection": 1 },
    { "english": "bank", "russian": "банк", "section": 1, "subsection": 1 },
    { "english": "base", "russian": "основной", "section": 1, "subsection": 2 },
    { "english": "basin", "russian": "бассейн", "section": 1, "subsection": 1 },
    { "english": "basket", "russian": "корзина", "section": 1, "subsection": 1 },
    { "english": "bath", "russian": "ванна, купаться", "section": 1, "subsection": 1 },
    { "english": "be", "russian": "быть", "section": 2, "subsection": 0 },
    { "english": "beautiful", "russian": "красивый", "section": 3, "subsection": 1 },
    { "english": "because", "russian": "потому что", "section": 2, "subsection": 0 },
    { "english": "bed", "russian": "кровать", "section": 1, "subsection": 1 },
    { "english": "bee", "russian": "пчела", "section": 1, "subsection": 1 },
    { "english": "before", "russian": "перед", "section": 2, "subsection": 0 },
    { "english": "behaviour", "russian": "поведение", "section": 1, "subsection": 2 },
    { "english": "belief", "russian": "вера", "section": 1, "subsection": 2 },
    { "english": "bell", "russian": "колокольчик", "section": 1, "subsection": 1 },
    { "english": "bent", "russian": "склонность, сгибать", "section": 3, "subsection": 2 },
    { "english": "berry", "russian": "ягода", "section": 1, "subsection": 1 },
    { "english": "between", "russian": "между", "section": 2, "subsection": 0 },
    { "english": "bird", "russian": "птица", "section": 1, "subsection": 1 },
    { "english": "birth", "russian": "рождение", "section": 1, "subsection": 2 },
    { "english": "bit", "russian": "частица, бит", "section": 1, "subsection": 2 },
    { "english": "bite", "russian": "укус, кусать", "section": 1, "subsection": 2 },
    { "english": "bitter", "russian": "горький, ожесточенный", "section": 3, "subsection": 2 },
    { "english": "black", "russian": "чёрный", "section": 3, "subsection": 1 },
    { "english": "blade", "russian": "лезвие", "section": 1, "subsection": 1 },
    { "english": "blood", "russian": "кровь", "section": 1, "subsection": 2 },
    { "english": "blow", "russian": "удар, дуть", "section": 1, "subsection": 2 },
    { "english": "blue", "russian": "синий", "section": 3, "subsection": 2 },
    { "english": "board", "russian": "доска", "section": 1, "subsection": 1 },
    { "english": "boat", "russian": "лодка, судно", "section": 1, "subsection": 1 },
    { "english": "body", "russian": "тело", "section": 1, "subsection": 2 },
    { "english": "boiling", "russian": "кипение", "section": 3, "subsection": 1 },
    { "english": "bone", "russian": "кость", "section": 1, "subsection": 1 },
    { "english": "book", "russian": "книга", "section": 1, "subsection": 1 },
    { "english": "boot", "russian": "ботинок, загружать", "section": 1, "subsection": 1 },
    { "english": "bottle", "russian": "бутылка", "section": 1, "subsection": 1 },
    { "english": "box", "russian": "коробка", "section": 1, "subsection": 1 },
    { "english": "boy", "russian": "мальчик", "section": 1, "subsection": 1 },
    { "english": "brain", "russian": "мозг", "section": 1, "subsection": 1 },
    { "english": "brake", "russian": "тормоз, тормозить", "section": 1, "subsection": 1 },
    { "english": "branch", "russian": "ветвь, отделение", "section": 1, "subsection": 1 },
    { "english": "brass", "russian": "медь, руководство", "section": 1, "subsection": 2 },
    { "english": "bread", "russian": "хлеб", "section": 1, "subsection": 2 },
    { "english": "breath", "russian": "дыхание", "section": 1, "subsection": 2 },
    { "english": "brick", "russian": "кирпич", "section": 1, "subsection": 1 },
    { "english": "bridge", "russian": "мост", "section": 1, "subsection": 1 },
    { "english": "bright", "russian": "яркий, умный", "section": 3, "subsection": 1 },
    { "english": "broken", "russian": "сломанный", "section": 3, "subsection": 1 },
    { "english": "brother", "russian": "брат", "section": 1, "subsection": 2 },
    { "english": "brown", "russian": "коричневый", "section": 3, "subsection": 1 },
    { "english": "brush", "russian": "щётка, кисть", "section": 1, "subsection": 1 },
    { "english": "bucket", "russian": "ведро, черпать", "section": 1, "subsection": 1 },
    { "english": "building", "russian": "здание, строение", "section": 1, "subsection": 2 },
    { "english": "bulb", "russian": "луковица, выпирать", "section": 1, "subsection": 1 },
    { "english": "burn", "russian": "ожог, гореть", "section": 1, "subsection": 2 },
    { "english": "burst", "russian": "взрыв, взрывать", "section": 1, "subsection": 2 },
    { "english": "business", "russian": "бизнес, деловой", "section": 1, "subsection": 2 },
    { "english": "but", "russian": "а, но", "section": 2, "subsection": 0 },
    { "english": "butter", "russian": "масло", "section": 1, "subsection": 2 },
    { "english": "button", "russian": "кнопка, застёгивать", "section": 1, "subsection": 1 },
    { "english": "by", "russian": "к, в соответствии с, за, на", "section": 2, "subsection": 0 },
    { "english": "cake", "russian": "пирог", "section": 1, "subsection": 1 },
    { "english": "camera", "russian": "камера", "section": 1, "subsection": 1 },
    { "english": "canvas", "russian": "холст", "section": 1, "subsection": 2 },
    { "english": "card", "russian": "карта, чесать", "section": 1, "subsection": 1 },
    { "english": "care", "russian": "забота, лечение", "section": 1, "subsection": 2 },
    { "english": "carriage", "russian": "вагон", "section": 1, "subsection": 1 },
    { "english": "cart", "russian": "везти", "section": 1, "subsection": 1 },
    { "english": "cat", "russian": "кот", "section": 1, "subsection": 1 },
    { "english": "cause", "russian": "причина, вызывать", "section": 1, "subsection": 2 },
    { "english": "certain", "russian": "уверенный, определенный", "section": 3, "subsection": 2 },
    { "english": "chain", "russian": "цепь, сеть", "section": 1, "subsection": 1 },
    { "english": "chalk", "russian": "мел, рисовать мелом", "section": 1, "subsection": 2 },
    { "english": "chance", "russian": "шанс, случайный, рисковать", "section": 1, "subsection": 2 },
    { "english": "change", "russian": "изменение, замена", "section": 1, "subsection": 2 },
    { "english": "cheap", "russian": "дешёвый", "section": 3, "subsection": 1 },
    { "english": "cheese", "russian": "сыр", "section": 1, "subsection": 1 },
    { "english": "chemical", "russian": "химикат", "section": 3, "subsection": 1 },
    { "english": "chest", "russian": "грудь, сундук", "section": 1, "subsection": 1 },
    { "english": "chief", "russian": "главный", "section": 3, "subsection": 1 },
    { "english": "chin", "russian": "подбородок", "section": 1, "subsection": 1 },
    { "english": "church", "russian": "церковь", "section": 1, "subsection": 1 },
    { "english": "circle", "russian": "круг", "section": 1, "subsection": 1 },
    { "english": "clean", "russian": "чистый, чистить", "section": 3, "subsection": 1 },
    { "english": "clear", "russian": "ясный, очищать, оправдываться", "section": 3, "subsection": 1 },
    { "english": "clock", "russian": "часы", "section": 1, "subsection": 1 },
    { "english": "cloth", "russian": "ткань, одежда", "section": 1, "subsection": 2 },
    { "english": "cloud", "russian": "облако", "section": 1, "subsection": 1 },
    { "english": "coal", "russian": "уголь", "section": 1, "subsection": 2 },
    { "english": "coat", "russian": "пальто, покрывать", "section": 1, "subsection": 1 },
    { "english": "cold", "russian": "холодный", "section": 3, "subsection": 2 },
    { "english": "collar", "russian": "воротник, хватать", "section": 1, "subsection": 1 },
    { "english": "colour", "russian": "цвет", "section": 1, "subsection": 2 },
    { "english": "comb", "russian": "расчёсывать", "section": 1, "subsection": 1 },
    { "english": "come", "russian": "приходить, приезжать", "section": 2, "subsection": 0 },
    { "english": "comfort", "russian": "комфорт", "section": 1, "subsection": 2 },
    { "english": "committee", "russian": "комитет", "section": 1, "subsection": 2 },
    { "english": "common", "russian": "общий", "section": 3, "subsection": 1 },
    { "english": "company", "russian": "компания", "section": 1, "subsection": 2 },
    { "english": "comparison", "russian": "сравнение", "section": 1, "subsection": 2 },
    { "english": "competition", "russian": "соревнование", "section": 1, "subsection": 2 },
    { "english": "complete", "russian": "полный, заканчивать", "section": 3, "subsection": 2 },
    { "english": "complex", "russian": "комплекс", "section": 3, "subsection": 1 },
    { "english": "condition", "russian": "условие, обуславливать", "section": 1, "subsection": 2 },
    { "english": "connection", "russian": "связь", "section": 1, "subsection": 2 },
    { "english": "conscious", "russian": "сознательный", "section": 3, "subsection": 1 },
    { "english": "control", "russian": "контроль", "section": 1, "subsection": 2 },
    { "english": "cook", "russian": "готовить", "section": 1, "subsection": 2 },
    { "english": "copper", "russian": "медь", "section": 1, "subsection": 2 },
    { "english": "copy", "russian": "копия", "section": 1, "subsection": 2 },
    { "english": "cord", "russian": "шнур, связывать", "section": 1, "subsection": 1 },
    { "english": "cork", "russian": "пробка", "section": 1, "subsection": 2 },
    { "english": "cotton", "russian": "хлопок", "section": 1, "subsection": 2 },
    { "english": "cough", "russian": "кашель", "section": 1, "subsection": 2 },
    { "english": "country", "russian": "страна", "section": 1, "subsection": 2 },
    { "english": "cover", "russian": "покрытие, покрывать, обложка", "section": 1, "subsection": 2 },
    { "english": "cow", "russian": "корова", "section": 1, "subsection": 1 },
    { "english": "crack", "russian": "первоклассный, взламывать", "section": 1, "subsection": 2 },
    { "english": "credit", "russian": "кредит, верить", "section": 1, "subsection": 2 },
    { "english": "crime", "russian": "преступление", "section": 1, "subsection": 2 },
    { "english": "cruel", "russian": "жестокий", "section": 3, "subsection": 2 },
    { "english": "crush", "russian": "давка, сокрушать", "section": 1, "subsection": 2 },
    { "english": "cry", "russian": "плакать", "section": 1, "subsection": 2 },
    { "english": "cup", "russian": "чашка", "section": 1, "subsection": 1 },
    { "english": "current", "russian": "текущий, поток", "section": 1, "subsection": 2 },
    { "english": "curtain", "russian": "занавес, штора, занавешивать", "section": 1, "subsection": 1 },
    { "english": "curve", "russian": "кривая, избегать", "section": 1, "subsection": 2 },
    { "english": "cushion", "russian": "подушка, смягчать", "section": 1, "subsection": 1 },
    { "english": "cut", "russian": "резать", "section": 3, "subsection": 1 },
    { "english": "damage", "russian": "повреждение, повреждать", "section": 1, "subsection": 2 },
    { "english": "danger", "russian": "опасность", "section": 1, "subsection": 2 },
    { "english": "dark", "russian": "темнота, темный", "section": 3, "subsection": 2 },
    { "english": "daughter", "russian": "дочь", "section": 1, "subsection": 2 },
    { "english": "day", "russian": "день", "section": 1, "subsection": 2 },
    { "english": "dead", "russian": "мёртвый", "section": 3, "subsection": 2 },
    { "english": "dear", "russian": "дорогой", "section": 3, "subsection": 2 },
    { "english": "death", "russian": "смерть", "section": 1, "subsection": 2 },
    { "english": "debt", "russian": "долг", "section": 1, "subsection": 2 },
    { "english": "decision", "russian": "решение", "section": 1, "subsection": 2 },
    { "english": "deep", "russian": "глубокий, глубоко", "section": 3, "subsection": 1 },
    { "english": "degree", "russian": "уровень, градус, степень", "section": 1, "subsection": 2 },
    { "english": "delicate", "russian": "тонкий, деликатный", "section": 3, "subsection": 2 },
    { "english": "dependent", "russian": "зависимый", "section": 3, "subsection": 1 },
    { "english": "design", "russian": "намереваться", "section": 1, "subsection": 2 },
    { "english": "desire", "russian": "желание, желать", "section": 1, "subsection": 2 },
    { "english": "destruction", "russian": "разрушение", "section": 1, "subsection": 2 },
    { "english": "detail", "russian": "детализировать, детали", "section": 1, "subsection": 2 },
    { "english": "development", "russian": "развитие", "section": 1, "subsection": 2 },
    { "english": "different", "russian": "различный, другой", "section": 3, "subsection": 2 },
    { "english": "digestion", "russian": "вываривание", "section": 1, "subsection": 2 },
    { "english": "direction", "russian": "управление", "section": 1, "subsection": 2 },
    { "english": "dirty", "russian": "грязный", "section": 3, "subsection": 2 },
    { "english": "discovery", "russian": "открытие", "section": 1, "subsection": 2 },
    { "english": "discussion", "russian": "обсуждение", "section": 1, "subsection": 2 },
    { "english": "disease", "russian": "болезнь", "section": 1, "subsection": 2 },
    { "english": "disgust", "russian": "отвращение", "section": 1, "subsection": 2 },
    { "english": "distance", "russian": "дистанция", "section": 1, "subsection": 2 },
    { "english": "distribution", "russian": "распределение", "section": 1, "subsection": 2 },
    { "english": "division", "russian": "подразделение", "section": 1, "subsection": 2 },
    { "english": "do", "russian": "делать", "section": 2, "subsection": 0 },
    { "english": "dog", "russian": "собака", "section": 1, "subsection": 1 },
    { "english": "door", "russian": "дверь", "section": 1, "subsection": 1 },
    { "english": "doubt", "russian": "сомнение", "section": 1, "subsection": 2 },
    { "english": "down", "russian": "вниз", "section": 2, "subsection": 0 },
    { "english": "drain", "russian": "утечка, истощать", "section": 1, "subsection": 1 },
    { "english": "drawer", "russian": "ящик", "section": 1, "subsection": 1 },
    { "english": "dress", "russian": "платье, одевать", "section": 1, "subsection": 1 },
    { "english": "drink", "russian": "пить, напиток", "section": 1, "subsection": 2 },
    { "english": "driving", "russian": "вождение", "section": 1, "subsection": 2 },
    { "english": "drop", "russian": "капля, опускать", "section": 1, "subsection": 1 },
    { "english": "dry", "russian": "сухой, сушить", "section": 3, "subsection": 2 },
    { "english": "dust", "russian": "чистить, пыль", "section": 1, "subsection": 2 },
    { "english": "ear", "russian": "ухо", "section": 1, "subsection": 1 },
    { "english": "early", "russian": "рано, ранний", "section": 3, "subsection": 1 },
    { "english": "earth", "russian": "земля", "section": 1, "subsection": 2 },
    { "english": "east", "russian": "восток", "section": 2, "subsection": 0 },
    { "english": "edge", "russian": "продвигаться, край", "section": 1, "subsection": 2 },
    { "english": "education", "russian": "образование", "section": 1, "subsection": 2 },
    { "english": "effect", "russian": "производить, эффект", "section": 1, "subsection": 2 },
    { "english": "egg", "russian": "яйцо", "section": 1, "subsection": 1 },
    { "english": "elastic", "russian": "эластичный", "section": 3, "subsection": 1 },
    { "english": "electric", "russian": "электрический", "section": 3, "subsection": 1 },
    { "english": "end", "russian": "заканчивать, конец", "section": 1, "subsection": 2 },
    { "english": "engine", "russian": "двигатель", "section": 1, "subsection": 1 },
    { "english": "enough", "russian": "достаточно", "section": 2, "subsection": 0 },
    { "english": "equal", "russian": "равный, равняться", "section": 3, "subsection": 1 },
    { "english": "error", "russian": "ошибка", "section": 1, "subsection": 2 },
    { "english": "even", "russian": "еще, даже", "section": 2, "subsection": 0 },
    { "english": "event", "russian": "случай, событие", "section": 1, "subsection": 2 },
    { "english": "ever", "russian": "когда-либо, никогда", "section": 2, "subsection": 0 },
    { "english": "every", "russian": "каждый", "section": 2, "subsection": 0 },
    { "english": "example", "russian": "пример", "section": 1, "subsection": 2 },
    { "english": "exchange", "russian": "обмен, обменивать", "section": 1, "subsection": 2 },
    { "english": "existence", "russian": "существование", "section": 1, "subsection": 2 },
    { "english": "expansion", "russian": "расширение", "section": 1, "subsection": 2 },
    { "english": "experience", "russian": "опыт, испытывать", "section": 1, "subsection": 2 },
    { "english": "expert", "russian": "опытный, эксперт", "section": 1, "subsection": 2 },
    { "english": "eye", "russian": "глаз", "section": 1, "subsection": 1 },
    { "english": "face", "russian": "лицо", "section": 1, "subsection": 1 },
    { "english": "fact", "russian": "факт", "section": 1, "subsection": 2 },
    { "english": "fall", "russian": "падение, осень", "section": 1, "subsection": 2 },
    { "english": "false", "russian": "фальшивый", "section": 3, "subsection": 2 },
    { "english": "family", "russian": "семья", "section": 1, "subsection": 2 },
    { "english": "far", "russian": "самый дальний", "section": 2, "subsection": 0 },
    { "english": "farm", "russian": "ферма", "section": 1, "subsection": 1 },
    { "english": "fat", "russian": "толстый, жир", "section": 3, "subsection": 1 },
    { "english": "father", "russian": "папа", "section": 1, "subsection": 2 },
    { "english": "fear", "russian": "бояться, страх", "section": 1, "subsection": 2 },
    { "english": "feather", "russian": "перо, украшать", "section": 1, "subsection": 1 },
    { "english": "feeble", "russian": "слабый", "section": 3, "subsection": 2 },
    { "english": "feeling", "russian": "чувство", "section": 1, "subsection": 2 },
    { "english": "female", "russian": "женский", "section": 3, "subsection": 2 },
    { "english": "fertile", "russian": "плодородный", "section": 3, "subsection": 1 },
    { "english": "fiction", "russian": "беллетристика, фикция", "section": 1, "subsection": 2 },
    { "english": "field", "russian": "область, поле, выставлять", "section": 1, "subsection": 2 },
    { "english": "fight", "russian": "борьба, бороться", "section": 1, "subsection": 2 },
    { "english": "finger", "russian": "палец", "section": 1, "subsection": 1 },
    { "english": "fire", "russian": "огонь", "section": 1, "subsection": 2 },
    { "english": "first", "russian": "первый", "section": 3, "subsection": 1 },
    { "english": "fish", "russian": "рыба", "section": 1, "subsection": 1 },
    { "english": "fixed", "russian": "неподвижный, неизменный", "section": 3, "subsection": 1 },
    { "english": "flag", "russian": "флаг, сигнализировать", "section": 1, "subsection": 1 },
    { "english": "flame", "russian": "пылать, пламя", "section": 1, "subsection": 2 },
    { "english": "flat", "russian": "плоский, квартира, плоскость", "section": 3, "subsection": 1 },
    { "english": "flight", "russian": "полет, рейс", "section": 1, "subsection": 2 },
    { "english": "floor", "russian": "пол, этаж, дно", "section": 1, "subsection": 1 },
    { "english": "flower", "russian": "цветок", "section": 1, "subsection": 2 },
    { "english": "fly", "russian": "муха, лететь", "section": 1, "subsection": 1 },
    { "english": "fold", "russian": "сгиб, сворачивать", "section": 1, "subsection": 2 },
    { "english": "food", "russian": "еда, продовольствие", "section": 1, "subsection": 2 },
    { "english": "foolish", "russian": "глупый", "section": 3, "subsection": 2 },
    { "english": "foot", "russian": "нога", "section": 1, "subsection": 1 },
    { "english": "for", "russian": "для", "section": 2, "subsection": 0 },
    { "english": "force", "russian": "сила, вынуждать, вызывать", "section": 1, "subsection": 2 },
    { "english": "fork", "russian": "вилка", "section": 1, "subsection": 1 },
    { "english": "form", "russian": "форма", "section": 1, "subsection": 2 },
    { "english": "forward", "russian": "отправлять, вперед", "section": 2, "subsection": 0 },
    { "english": "fowl", "russian": "домашняя птица", "section": 1, "subsection": 1 },
    { "english": "frame", "russian": "структура, рамка, создавать", "section": 1, "subsection": 1 },
    { "english": "free", "russian": "свобода, бесплатный", "section": 3, "subsection": 1 },
    { "english": "frequent", "russian": "частый, часто посещать", "section": 3, "subsection": 1 },
    { "english": "friend", "russian": "друг", "section": 1, "subsection": 2 },
    { "english": "from", "russian": "из", "section": 2, "subsection": 0 },
    { "english": "front", "russian": "выходить, фронт, передний", "section": 1, "subsection": 2 },
    { "english": "fruit", "russian": "фрукт", "section": 1, "subsection": 2 },
    { "english": "full", "russian": "полный", "section": 3, "subsection": 1 },
    { "english": "future", "russian": "будущий, будущее", "section": 3, "subsection": 2 },
    { "english": "garden", "russian": "сад", "section": 1, "subsection": 1 },
    { "english": "general", "russian": "общий, генерал", "section": 3, "subsection": 1 },
    { "english": "get", "russian": "получать, заставлять", "section": 2, "subsection": 0 },
    { "english": "girl", "russian": "девочка", "section": 1, "subsection": 1 },
    { "english": "give", "russian": "давать", "section": 2, "subsection": 0 },
    { "english": "glass", "russian": "стекло, стакан", "section": 1, "subsection": 2 },
    { "english": "glove", "russian": "перчатка", "section": 1, "subsection": 1 },
    { "english": "go", "russian": "ходить, идти", "section": 2, "subsection": 0 },
    { "english": "goat", "russian": "коза", "section": 1, "subsection": 1 },
    { "english": "gold", "russian": "золото", "section": 1, "subsection": 2 },
    { "english": "good", "russian": "хороший", "section": 3, "subsection": 1 },
    { "english": "government", "russian": "государство", "section": 1, "subsection": 2 },
    { "english": "grain", "russian": "зерно", "section": 1, "subsection": 2 },
    { "english": "grass", "russian": "трава", "section": 1, "subsection": 2 },
    { "english": "great", "russian": "великий, великолепный", "section": 3, "subsection": 1 },
    { "english": "green", "russian": "зелёный", "section": 3, "subsection": 2 },
    { "english": "grey/gray", "russian": "серый", "section": 3, "subsection": 1 },
    { "english": "grip", "russian": "власть, захват, захватывать", "section": 1, "subsection": 2 },
    { "english": "group", "russian": "группа", "section": 1, "subsection": 2 },
    { "english": "growth", "russian": "рост", "section": 1, "subsection": 2 },
    { "english": "guide", "russian": "гид, справочник, путеводитель", "section": 1, "subsection": 2 },
    { "english": "gun", "russian": "оружие", "section": 1, "subsection": 1 },
    { "english": "hair", "russian": "волосы", "section": 1, "subsection": 1 },
    { "english": "hammer", "russian": "молоток", "section": 1, "subsection": 1 },
    { "english": "hand", "russian": "рука", "section": 1, "subsection": 1 },
    { "english": "hanging", "russian": "вывешивание, висение", "section": 3, "subsection": 1 },
    { "english": "happy", "russian": "счастье", "section": 3, "subsection": 1 },
    { "english": "harbour", "russian": "приютить, питать, вставать на якорь, гавань", "section": 1, "subsection": 2 },
    { "english": "hard", "russian": "трудный, тяжёлый, твёрдый", "section": 3, "subsection": 1 },
    { "english": "harmony", "russian": "гармония", "section": 1, "subsection": 2 },
    { "english": "hat", "russian": "шляпа", "section": 1, "subsection": 1 },
    { "english": "hate", "russian": "ненавидеть, очень не хотеть, ненависть", "section": 1, "subsection": 2 },
    { "english": "have", "russian": "иметь, съесть, знать", "section": 2, "subsection": 0 },
    { "english": "he", "russian": "он", "section": 2, "subsection": 0 },
    { "english": "head", "russian": "голова", "section": 1, "subsection": 1 },
    { "english": "healthy", "russian": "здоровый", "section": 3, "subsection": 1 },
    { "english": "hearing", "russian": "слушание, слух", "section": 1, "subsection": 2 },
    { "english": "heart", "russian": "сердце", "section": 1, "subsection": 1 },
    { "english": "heat", "russian": "нагревать, высокая температура", "section": 1, "subsection": 2 },
    { "english": "help", "russian": "помощь, помогать", "section": 1, "subsection": 2 },
    { "english": "here", "russian": "здесь, сюда", "section": 2, "subsection": 0 },
    { "english": "high", "russian": "высокий, высоко", "section": 3, "subsection": 1 },
    { "english": "history", "russian": "история", "section": 1, "subsection": 2 },
    { "english": "hole", "russian": "продырявливать, отверстие", "section": 1, "subsection": 2 },
    { "english": "hollow", "russian": "пустота", "section": 3, "subsection": 1 },
    { "english": "hook", "russian": "крюк, вербовать", "section": 1, "subsection": 1 },
    { "english": "hope", "russian": "надежда, надеяться", "section": 1, "subsection": 2 },
    { "english": "horn", "russian": "рожок", "section": 1, "subsection": 1 },
    { "english": "horse", "russian": "лошадь", "section": 1, "subsection": 1 },
    { "english": "hospital", "russian": "больница", "section": 1, "subsection": 1 },
    { "english": "hour", "russian": "час", "section": 1, "subsection": 2 },
    { "english": "house", "russian": "дом", "section": 1, "subsection": 1 },
    { "english": "how", "russian": "как", "section": 2, "subsection": 0 },
    { "english": "humour", "russian": "юмор", "section": 1, "subsection": 2 },
    { "english": "i", "russian": "я", "section": 2, "subsection": 0 },
    { "english": "ice", "russian": "лёд", "section": 1, "subsection": 2 },
    { "english": "idea", "russian": "идея", "section": 1, "subsection": 2 },
    { "english": "if", "russian": "если", "section": 2, "subsection": 0 },
    { "english": "ill", "russian": "плохо, болеть", "section": 3, "subsection": 2 },
    { "english": "important", "russian": "важный", "section": 3, "subsection": 1 },
    { "english": "impulse", "russian": "импульс", "section": 1, "subsection": 2 },
    { "english": "in", "russian": "в", "section": 2, "subsection": 0 },
    { "english": "increase", "russian": "увеличивать, увеличение", "section": 1, "subsection": 2 },
    { "english": "industry", "russian": "индустрия", "section": 1, "subsection": 2 },
    { "english": "ink", "russian": "чернила", "section": 1, "subsection": 2 },
    { "english": "insect", "russian": "насекомое", "section": 1, "subsection": 2 },
    { "english": "instrument", "russian": "инструмент", "section": 1, "subsection": 2 },
    { "english": "insurance", "russian": "страховка", "section": 1, "subsection": 2 },
    { "english": "interest", "russian": "интерес, процент, доля", "section": 1, "subsection": 2 },
    { "english": "invention", "russian": "изобретение", "section": 1, "subsection": 2 },
    { "english": "iron", "russian": "утюг, гладить", "section": 1, "subsection": 2 },
    { "english": "island", "russian": "остров", "section": 1, "subsection": 1 },
    { "english": "jelly", "russian": "превращать в желе, желе", "section": 1, "subsection": 2 },
    { "english": "jewel", "russian": "драгоценный камень", "section": 1, "subsection": 1 },
    { "english": "join", "russian": "присоединяться, объединение, соединение", "section": 1, "subsection": 2 },
    { "english": "journey", "russian": "путешествовать, поездка", "section": 1, "subsection": 2 },
    { "english": "judge", "russian": "судья, судить", "section": 1, "subsection": 2 },
    { "english": "jump", "russian": "прыгать, прыжок", "section": 1, "subsection": 2 },
    { "english": "keep", "russian": "продолжать, держать, оставлять, не допускать", "section": 2, "subsection": 0 },
    { "english": "kettle", "russian": "чайник", "section": 1, "subsection": 1 },
    { "english": "key", "russian": "ключ", "section": 1, "subsection": 1 },
    { "english": "kick", "russian": "удар, ударить", "section": 1, "subsection": 2 },
    { "english": "kind", "russian": "добрый, вид", "section": 3, "subsection": 1 },
    { "english": "kiss", "russian": "поцелуй, целовать", "section": 1, "subsection": 2 },
    { "english": "knee", "russian": "колено", "section": 1, "subsection": 1 },
    { "english": "knife", "russian": "нож", "section": 1, "subsection": 1 },
    { "english": "knot", "russian": "узел", "section": 1, "subsection": 1 },
    { "english": "knowledge", "russian": "знание", "section": 1, "subsection": 2 },
    { "english": "land", "russian": "земля", "section": 1, "subsection": 2 },
    { "english": "language", "russian": "язык", "section": 1, "subsection": 2 },
    { "english": "last", "russian": "последний, длиться", "section": 3, "subsection": 2 },
    { "english": "late", "russian": "опаздывать", "section": 3, "subsection": 2 },
    { "english": "laugh", "russian": "смеяться, смех", "section": 1, "subsection": 2 },
    { "english": "law", "russian": "законный, закон", "section": 1, "subsection": 2 },
    { "english": "lead", "russian": "принуждать, побеждать, вести, лидерство", "section": 1, "subsection": 2 },
    { "english": "leaf", "russian": "лист, покрывать листвой", "section": 1, "subsection": 1 },
    { "english": "learning", "russian": "изучение, обучение", "section": 1, "subsection": 2 },
    { "english": "leather", "russian": "кожа", "section": 1, "subsection": 2 },
    { "english": "left", "russian": "лево, левый", "section": 3, "subsection": 2 },
    { "english": "leg", "russian": "нога", "section": 1, "subsection": 1 },
    { "english": "let", "russian": "позволять", "section": 2, "subsection": 0 },
    { "english": "letter", "russian": "письмо", "section": 1, "subsection": 2 },
    { "english": "level", "russian": "уровень, выравнивать, направлять", "section": 1, "subsection": 2 },
    { "english": "library", "russian": "библиотека", "section": 1, "subsection": 1 },
    { "english": "lift", "russian": "поднимать, лифт", "section": 1, "subsection": 2 },
    { "english": "light", "russian": "освещать, легкий, свет", "section": 1, "subsection": 2 },
    { "english": "like", "russian": "подобный, любить, нравиться", "section": 3, "subsection": 1 },
    { "english": "limit", "russian": "ограничивать", "section": 1, "subsection": 2 },
    { "english": "line", "russian": "линия, очередь, выравнивать", "section": 1, "subsection": 1 },
    { "english": "linen", "russian": "льняной, полотно", "section": 1, "subsection": 2 },
    { "english": "lip", "russian": "губа", "section": 1, "subsection": 1 },
    { "english": "liquid", "russian": "жидкий, жидкость", "section": 1, "subsection": 2 },
    { "english": "list", "russian": "список, перечислять", "section": 1, "subsection": 2 },
    { "english": "little", "russian": "маленький", "section": 2, "subsection": 0 },
    { "english": "living", "russian": "проживаниe", "section": 3, "subsection": 1 },
    { "english": "lock", "russian": "замок", "section": 1, "subsection": 1 },
    { "english": "long", "russian": "долго, длинный", "section": 3, "subsection": 1 },
    { "english": "look", "russian": "вид, внешность", "section": 1, "subsection": 2 },
    { "english": "loose", "russian": "свободный, освобождать", "section": 3, "subsection": 2 },
    { "english": "loss", "russian": "потеря", "section": 1, "subsection": 2 },
    { "english": "loud", "russian": "громкий", "section": 3, "subsection": 2 },
    { "english": "love", "russian": "любовь", "section": 1, "subsection": 2 },
    { "english": "low", "russian": "низкий", "section": 3, "subsection": 2 },
    { "english": "machine", "russian": "машина", "section": 1, "subsection": 2 },
    { "english": "make", "russian": "делать/сделать, заставлять", "section": 2, "subsection": 0 },
    { "english": "male", "russian": "мужской, мужчина", "section": 3, "subsection": 2 },
    { "english": "man", "russian": "человек", "section": 1, "subsection": 2 },
    { "english": "manager", "russian": "менеджер, руководитель", "section": 1, "subsection": 2 },
    { "english": "map", "russian": "карта", "section": 1, "subsection": 1 },
    { "english": "mark", "russian": "марка", "section": 1, "subsection": 2 },
    { "english": "market", "russian": "рынок", "section": 1, "subsection": 2 },
    { "english": "married", "russian": "женатый, замужем", "section": 3, "subsection": 1 },
    { "english": "mass", "russian": "масса", "section": 1, "subsection": 2 },
    { "english": "match", "russian": "спичка, сделки, соответствовать", "section": 1, "subsection": 1 },
    { "english": "material", "russian": "материал", "section": 3, "subsection": 1 },
    { "english": "may", "russian": "мочь", "section": 2, "subsection": 0 },
    { "english": "meal", "russian": "еда", "section": 1, "subsection": 2 },
    { "english": "measure", "russian": "мера, измерять", "section": 1, "subsection": 2 },
    { "english": "meat", "russian": "мясо", "section": 1, "subsection": 2 },
    { "english": "medical", "russian": "медицинский", "section": 3, "subsection": 1 },
    { "english": "meeting", "russian": "встреча", "section": 1, "subsection": 2 },
    { "english": "memory", "russian": "память", "section": 1, "subsection": 2 },
    { "english": "metal", "russian": "металл", "section": 1, "subsection": 2 },
    { "english": "middle", "russian": "средний, середина", "section": 1, "subsection": 2 },
    { "english": "military", "russian": "военный", "section": 3, "subsection": 1 },
    { "english": "milk", "russian": "молоко", "section": 1, "subsection": 2 },
    { "english": "mind", "russian": "ум, возражать", "section": 1, "subsection": 2 },
    { "english": "mine", "russian": "мой, месторождение, мина", "section": 1, "subsection": 2 },
    { "english": "minute", "russian": "минута", "section": 1, "subsection": 2 },
    { "english": "mist", "russian": "туман", "section": 1, "subsection": 2 },
    { "english": "mixed", "russian": "перемешанный", "section": 3, "subsection": 2 },
    { "english": "money", "russian": "деньги", "section": 1, "subsection": 2 },
    { "english": "monkey", "russian": "обезьяна", "section": 1, "subsection": 1 },
    { "english": "month", "russian": "месяц", "section": 1, "subsection": 2 },
    { "english": "moon", "russian": "луна", "section": 1, "subsection": 1 },
    { "english": "morning", "russian": "утро", "section": 1, "subsection": 2 },
    { "english": "mother", "russian": "мать", "section": 1, "subsection": 2 },
    { "english": "motion", "russian": "двигаться, движение, жест", "section": 1, "subsection": 2 },
    { "english": "mountain", "russian": "гора, горный", "section": 1, "subsection": 2 },
    { "english": "mouth", "russian": "рот, жевать", "section": 1, "subsection": 1 },
    { "english": "move", "russian": "двигать, шаг, движение", "section": 1, "subsection": 2 },
    { "english": "much", "russian": "много", "section": 2, "subsection": 0 },
    { "english": "muscle", "russian": "мускул", "section": 1, "subsection": 1 },
    { "english": "music", "russian": "музыка", "section": 1, "subsection": 2 },
    { "english": "nail", "russian": "ноготь", "section": 1, "subsection": 1 },
    { "english": "name", "russian": "имя", "section": 1, "subsection": 2 },
    { "english": "narrow", "russian": "узкий, сужаться", "section": 3, "subsection": 2 },
    { "english": "nation", "russian": "нация", "section": 1, "subsection": 2 },
    { "english": "natural", "russian": "натуральный", "section": 3, "subsection": 1 },
    { "english": "near", "russian": "рядом, около", "section": 2, "subsection": 0 },
    { "english": "necessary", "russian": "необходимый", "section": 3, "subsection": 1 },
    { "english": "neck", "russian": "шея, обниматься", "section": 1, "subsection": 1 },
    { "english": "need", "russian": "потребность, требоваться", "section": 1, "subsection": 2 },
    { "english": "needle", "russian": "игла", "section": 1, "subsection": 1 },
    { "english": "nerve", "russian": "нерв", "section": 1, "subsection": 1 },
    { "english": "net", "russian": "чистый, сеть", "section": 1, "subsection": 1 },
    { "english": "new", "russian": "новый", "section": 3, "subsection": 1 },
    { "english": "news", "russian": "новости", "section": 1, "subsection": 2 },
    { "english": "night", "russian": "ночь", "section": 1, "subsection": 2 },
    { "english": "no", "russian": "никакой, нет", "section": 2, "subsection": 0 },
    { "english": "noise", "russian": "шум", "section": 1, "subsection": 2 },
    { "english": "normal", "russian": "нормальный", "section": 3, "subsection": 1 },
    { "english": "north", "russian": "север", "section": 2, "subsection": 0 },
    { "english": "nose", "russian": "нос", "section": 1, "subsection": 1 },
    { "english": "not", "russian": "не", "section": 2, "subsection": 0 },
    { "english": "note", "russian": "примечание, отмечать", "section": 1, "subsection": 2 },
    { "english": "now", "russian": "теперь, сейчас", "section": 2, "subsection": 0 },
    { "english": "number", "russian": "число, номер", "section": 1, "subsection": 2 },
    { "english": "nut", "russian": "орех", "section": 1, "subsection": 1 },
    { "english": "observation", "russian": "наблюдение", "section": 1, "subsection": 2 },
    { "english": "of", "russian": "из, о, от", "section": 2, "subsection": 0 },
    { "english": "off", "russian": "прочь, от", "section": 2, "subsection": 0 },
    { "english": "offer", "russian": "предложение, предлагать", "section": 1, "subsection": 2 },
    { "english": "office", "russian": "офис", "section": 1, "subsection": 1 },
    { "english": "oil", "russian": "масло", "section": 1, "subsection": 2 },
    { "english": "old", "russian": "старый", "section": 3, "subsection": 2 },
    { "english": "on", "russian": "на", "section": 2, "subsection": 0 },
    { "english": "only", "russian": "только", "section": 2, "subsection": 0 },
    { "english": "open", "russian": "открытый, открывать", "section": 3, "subsection": 1 },
    { "english": "operation", "russian": "операция, действие", "section": 1, "subsection": 2 },
    { "english": "opinion", "russian": "мнение", "section": 1, "subsection": 2 },
    { "english": "opposite", "russian": "напротив, противоположный", "section": 3, "subsection": 2 },
    { "english": "or", "russian": "или", "section": 2, "subsection": 0 },
    { "english": "orange", "russian": "апельсин, оранжевый", "section": 1, "subsection": 1 },
    { "english": "order", "russian": "заказ, заказывать, приказывать", "section": 1, "subsection": 2 },
    { "english": "organization", "russian": "организация", "section": 1, "subsection": 2 },
    { "english": "ornament", "russian": "украшение, украшать", "section": 1, "subsection": 2 },
    { "english": "other", "russian": "другой", "section": 2, "subsection": 0 },
    { "english": "out", "russian": "вне, снаружи", "section": 2, "subsection": 0 },
    { "english": "oven", "russian": "духовка, печь", "section": 1, "subsection": 1 },
    { "english": "over", "russian": "по", "section": 2, "subsection": 0 },
    { "english": "owner", "russian": "владелец", "section": 1, "subsection": 2 },
    { "english": "page", "russian": "страница", "section": 1, "subsection": 2 },
    { "english": "pain", "russian": "боль, причинять боль", "section": 1, "subsection": 2 },
    { "english": "paint", "russian": "краска, рисовать, красить", "section": 1, "subsection": 2 },
    { "english": "paper", "russian": "бумага", "section": 1, "subsection": 2 },
    { "english": "parallel", "russian": "параллельный, находить что-либо подобное", "section": 3, "subsection": 1 },
    { "english": "parcel", "russian": "пакет, распределять", "section": 1, "subsection": 1 },
    { "english": "part", "russian": "часть, отделять, разделяться", "section": 1, "subsection": 2 },
    { "english": "past", "russian": "мимо, прошлый", "section": 3, "subsection": 1 },
    { "english": "paste", "russian": "приклеивать, паста", "section": 1, "subsection": 2 },
    { "english": "payment", "russian": "оплата", "section": 1, "subsection": 2 },
    { "english": "peace", "russian": "мир", "section": 1, "subsection": 2 },
    { "english": "pen", "russian": "ручка", "section": 1, "subsection": 1 },
    { "english": "pencil", "russian": "карандаш", "section": 1, "subsection": 1 },
    { "english": "person", "russian": "персона", "section": 1, "subsection": 2 },
    { "english": "physical", "russian": "физический", "section": 3, "subsection": 1 },
    { "english": "picture", "russian": "картина", "section": 1, "subsection": 1 },
    { "english": "pig", "russian": "свинья", "section": 1, "subsection": 1 },
    { "english": "pin", "russian": "булавка, прикреплять", "section": 1, "subsection": 1 },
    { "english": "pipe", "russian": "труба", "section": 1, "subsection": 1 },
    { "english": "place", "russian": "размещать, помещать, занимать место, место", "section": 1, "subsection": 2 },
    { "english": "plane", "russian": "самолёт", "section": 1, "subsection": 1 },
    { "english": "plant", "russian": "завод, растение, прививать, сеять", "section": 1, "subsection": 2 },
    { "english": "plate", "russian": "пластина", "section": 1, "subsection": 1 },
    { "english": "play", "russian": "играть", "section": 1, "subsection": 2 },
    { "english": "please", "russian": "пожалуйста", "section": 2, "subsection": 0 },
    { "english": "pleasure", "russian": "удовольствие", "section": 1, "subsection": 2 },
    { "english": "plow", "russian": "плуг, пахать", "section": 1, "subsection": 1 },
    { "english": "pocket", "russian": "карман, присваивать", "section": 1, "subsection": 1 },
    { "english": "point", "russian": "пункт, точка, указывать", "section": 1, "subsection": 2 },
    { "english": "poison", "russian": "яд, отравлять", "section": 1, "subsection": 2 },
    { "english": "polish", "russian": "полировать", "section": 1, "subsection": 2 },
    { "english": "political", "russian": "политический", "section": 3, "subsection": 1 },
    { "english": "poor", "russian": "бедный, плохой, слабый", "section": 3, "subsection": 1 },
    { "english": "porter", "russian": "швейцар, носильщик", "section": 1, "subsection": 2 },
    { "english": "position", "russian": "помещать, позиция", "section": 1, "subsection": 2 },
    { "english": "possible", "russian": "возможный", "section": 3, "subsection": 1 },
    { "english": "pot", "russian": "горшок", "section": 1, "subsection": 1 },
    { "english": "potato", "russian": "картофель", "section": 1, "subsection": 1 },
    { "english": "powder", "russian": "порошок", "section": 1, "subsection": 2 },
    { "english": "power", "russian": "сила, власть", "section": 1, "subsection": 2 },
    { "english": "present", "russian": "существующий, подарок", "section": 3, "subsection": 1 },
    { "english": "price", "russian": "цена", "section": 1, "subsection": 2 },
    { "english": "print", "russian": "печатать", "section": 1, "subsection": 2 },
    { "english": "prison", "russian": "тюрьма", "section": 1, "subsection": 1 },
    { "english": "private", "russian": "личный, приватный", "section": 3, "subsection": 1 },
    { "english": "probable", "russian": "вероятный", "section": 3, "subsection": 1 },
    { "english": "process", "russian": "обрабатывать, процесс", "section": 1, "subsection": 2 },
    { "english": "produce", "russian": "продукт, производить", "section": 1, "subsection": 2 },
    { "english": "profit", "russian": "прибыль, получать прибыль", "section": 1, "subsection": 2 },
    { "english": "property", "russian": "свойства", "section": 1, "subsection": 2 },
    { "english": "prose", "russian": "проза", "section": 1, "subsection": 2 },
    { "english": "protest", "russian": "возражать, протест", "section": 1, "subsection": 2 },
    { "english": "public", "russian": "публичный", "section": 3, "subsection": 2 },
    { "english": "pull", "russian": "напряжение, тянуть", "section": 1, "subsection": 2 },
    { "english": "pump", "russian": "насос, качать", "section": 1, "subsection": 1 },
    { "english": "punishment", "russian": "наказание", "section": 1, "subsection": 2 },
    { "english": "purpose", "russian": "намереваться, цель", "section": 1, "subsection": 2 },
    { "english": "push", "russian": "толчок, подталкивать", "section": 1, "subsection": 2 },
    { "english": "put", "russian": "помещать", "section": 2, "subsection": 0 },
    { "english": "quality", "russian": "качество, качественный", "section": 1, "subsection": 2 },
    { "english": "question", "russian": "вопрос", "section": 1, "subsection": 2 },
    { "english": "quick", "russian": "быстрый", "section": 3, "subsection": 1 },
    { "english": "quiet", "russian": "тихий, успокаивать", "section": 3, "subsection": 1 },
    { "english": "quite", "russian": "весьма", "section": 2, "subsection": 0 },
    { "english": "rail", "russian": "рельс, перевозить поездом", "section": 1, "subsection": 1 },
    { "english": "rain", "russian": "дождь", "section": 1, "subsection": 2 },
    { "english": "range", "russian": "диапазон, располагаться", "section": 1, "subsection": 2 },
    { "english": "rat", "russian": "крыса", "section": 1, "subsection": 1 },
    { "english": "rate", "russian": "норма, разряд", "section": 1, "subsection": 2 },
    { "english": "ray", "russian": "луч", "section": 1, "subsection": 2 },
    { "english": "reaction", "russian": "реакция", "section": 1, "subsection": 2 },
    { "english": "read", "russian": "читать", "section": 3, "subsection": 1 },
    { "english": "reading", "russian": "чтение", "section": 1, "subsection": 2 },
    { "english": "ready", "russian": "готовый, готов", "section": 3, "subsection": 1 },
    { "english": "reason", "russian": "рассуждать, причина, разум", "section": 1, "subsection": 2 },
    { "english": "receipt", "russian": "квитанция", "section": 1, "subsection": 1 },
    { "english": "record", "russian": "рекордный, отчёт, делать запись", "section": 1, "subsection": 2 },
    { "english": "red", "russian": "красный", "section": 3, "subsection": 1 },
    { "english": "regret", "russian": "сожаление, сожалеть", "section": 1, "subsection": 2 },
    { "english": "regular", "russian": "регулярный", "section": 3, "subsection": 1 },
    { "english": "relation", "russian": "отношение", "section": 1, "subsection": 2 },
    { "english": "religion", "russian": "религия", "section": 1, "subsection": 2 },
    { "english": "representative", "russian": "представитель", "section": 1, "subsection": 2 },
    { "english": "request", "russian": "запрос, просить", "section": 1, "subsection": 2 },
    { "english": "respect", "russian": "уважение, уважать", "section": 1, "subsection": 2 },
    { "english": "responsible", "russian": "ответственный", "section": 3, "subsection": 1 },
    { "english": "rest", "russian": "отдых, отдыхать, оставаться", "section": 1, "subsection": 2 },
    { "english": "reward", "russian": "награда, вознаграждать", "section": 1, "subsection": 2 },
    { "english": "rhythm", "russian": "ритм", "section": 1, "subsection": 2 },
    { "english": "rice", "russian": "рис", "section": 1, "subsection": 2 },
    { "english": "right", "russian": "верный, право", "section": 3, "subsection": 1 },
    { "english": "ring", "russian": "кольцо, звонить", "section": 1, "subsection": 1 },
    { "english": "river", "russian": "река", "section": 1, "subsection": 2 },
    { "english": "road", "russian": "дорога", "section": 1, "subsection": 2 },
    { "english": "rod", "russian": "прут", "section": 1, "subsection": 1 },
    { "english": "roll", "russian": "рулон, ведомость, катиться, въезжать", "section": 1, "subsection": 2 },
    { "english": "roof", "russian": "крыша", "section": 1, "subsection": 1 },
    { "english": "room", "russian": "комната", "section": 1, "subsection": 2 },
    { "english": "root", "russian": "корень", "section": 1, "subsection": 1 },
    { "english": "rough", "russian": "грубый", "section": 3, "subsection": 2 },
    { "english": "round", "russian": "вокруг, круглый, раунд", "section": 3, "subsection": 1 },
    { "english": "rub", "russian": "протирать, тереться", "section": 1, "subsection": 2 },
    { "english": "rule", "russian": "правило", "section": 1, "subsection": 2 },
    { "english": "run", "russian": "бег, бегать", "section": 1, "subsection": 2 },
    { "english": "sad", "russian": "расстроенный", "section": 3, "subsection": 2 },
    { "english": "safe", "russian": "безопасный", "section": 3, "subsection": 2 },
    { "english": "sail", "russian": "парус", "section": 1, "subsection": 1 },
    { "english": "salt", "russian": "соль, солить", "section": 1, "subsection": 2 },
    { "english": "same", "russian": "то же самое", "section": 3, "subsection": 1 },
    { "english": "sand", "russian": "песок", "section": 1, "subsection": 2 },
    { "english": "say", "russian": "говорить", "section": 2, "subsection": 0 },
    { "english": "scale", "russian": "измерять, масштаб", "section": 1, "subsection": 2 },
    { "english": "school", "russian": "школа", "section": 1, "subsection": 1 },
    { "english": "science", "russian": "наука", "section": 1, "subsection": 2 },
    { "english": "scissors", "russian": "ножницы", "section": 1, "subsection": 1 },
    { "english": "screw", "russian": "винт", "section": 1, "subsection": 1 },
    { "english": "sea", "russian": "море", "section": 1, "subsection": 2 },
    { "english": "seat", "russian": "сиденье, усаживать, место", "section": 1, "subsection": 2 },
    { "english": "second", "russian": "секунда, второй", "section": 3, "subsection": 1 },
    { "english": "secret", "russian": "секретный", "section": 3, "subsection": 2 },
    { "english": "secretary", "russian": "секретарь", "section": 1, "subsection": 2 },
    { "english": "see", "russian": "видеть", "section": 2, "subsection": 0 },
    { "english": "seed", "russian": "семя", "section": 1, "subsection": 1 },
    { "english": "seem", "russian": "казаться, представляться", "section": 2, "subsection": 0 },
    { "english": "selection", "russian": "выбор", "section": 1, "subsection": 2 },
    { "english": "self", "russian": "сам", "section": 1, "subsection": 2 },
    { "english": "send", "russian": "посылать", "section": 2, "subsection": 0 },
    { "english": "sense", "russian": "чувство, значения, смысл, ощущать", "section": 1, "subsection": 2 },
    { "english": "separate", "russian": "отдельный, отделять", "section": 3, "subsection": 1 },
    { "english": "serious", "russian": "серьёзный", "section": 3, "subsection": 1 },
    { "english": "servant", "russian": "слуга", "section": 1, "subsection": 2 },
    { "english": "sex", "russian": "секс, пол", "section": 1, "subsection": 2 },
    { "english": "shade", "russian": "оттенок, тень, заштриховывать", "section": 1, "subsection": 2 },
    { "english": "shake", "russian": "встряска, встряхивать, дрожать, потрясать", "section": 1, "subsection": 2 },
    { "english": "shame", "russian": "позор, позорить", "section": 1, "subsection": 2 },
    { "english": "sharp", "russian": "острый", "section": 3, "subsection": 1 },
    { "english": "sheep", "russian": "овцы", "section": 1, "subsection": 1 },
    { "english": "shelf", "russian": "полка", "section": 1, "subsection": 1 },
    { "english": "ship", "russian": "корабль", "section": 1, "subsection": 1 },
    { "english": "shirt", "russian": "рубашка", "section": 1, "subsection": 1 },
    { "english": "shock", "russian": "шок, потрясать", "section": 1, "subsection": 2 },
    { "english": "shoe", "russian": "ботинок", "section": 1, "subsection": 1 },
    { "english": "short", "russian": "короткий", "section": 3, "subsection": 2 },
    { "english": "side", "russian": "сторона, примыкать", "section": 1, "subsection": 2 },
    { "english": "sign", "russian": "знак, признак, подписывать", "section": 1, "subsection": 2 },
    { "english": "silk", "russian": "шёлк", "section": 1, "subsection": 2 },
    { "english": "silver", "russian": "серебро", "section": 1, "subsection": 2 },
    { "english": "simple", "russian": "простой", "section": 3, "subsection": 2 },
    { "english": "sister", "russian": "сестра", "section": 1, "subsection": 2 },
    { "english": "size", "russian": "размер", "section": 1, "subsection": 2 },
    { "english": "skin", "russian": "кожа, очищать", "section": 1, "subsection": 1 },
    { "english": "skirt", "russian": "юбка", "section": 1, "subsection": 1 },
    { "english": "sky", "russian": "небо", "section": 1, "subsection": 2 },
    { "english": "sleep", "russian": "спать", "section": 1, "subsection": 2 },
    { "english": "slip", "russian": "промах, бланк, подсовывать, скользить", "section": 1, "subsection": 2 },
    { "english": "slope", "russian": "наклон, клониться", "section": 1, "subsection": 2 },
    { "english": "slow", "russian": "медленный", "section": 3, "subsection": 2 },
    { "english": "small", "russian": "маленький", "section": 3, "subsection": 2 },
    { "english": "smash", "russian": "удар, разбиваться", "section": 1, "subsection": 2 },
    { "english": "smell", "russian": "запах, пахнуть", "section": 1, "subsection": 2 },
    { "english": "smile", "russian": "улыбка, улыбаться", "section": 1, "subsection": 2 },
    { "english": "smoke", "russian": "дым, курить", "section": 1, "subsection": 2 },
    { "english": "smooth", "russian": "гладкий, мягкий, приглаживать", "section": 3, "subsection": 1 },
    { "english": "snake", "russian": "змея", "section": 1, "subsection": 1 },
    { "english": "sneeze", "russian": "чиханье, чихать", "section": 1, "subsection": 2 },
    { "english": "snow", "russian": "снег", "section": 1, "subsection": 2 },
    { "english": "so", "russian": "так", "section": 2, "subsection": 0 },
    { "english": "soap", "russian": "мыло, мылить", "section": 1, "subsection": 2 },
    { "english": "society", "russian": "общество", "section": 1, "subsection": 2 },
    { "english": "sock", "russian": "носок", "section": 1, "subsection": 1 },
    { "english": "soft", "russian": "мягкий", "section": 3, "subsection": 2 },
    { "english": "solid", "russian": "твёрдый, солидный", "section": 3, "subsection": 2 },
    { "english": "some", "russian": "некоторый, немного", "section": 2, "subsection": 0 },
    { "english": "son", "russian": "сын", "section": 1, "subsection": 2 },
    { "english": "song", "russian": "песня", "section": 1, "subsection": 2 },
    { "english": "sort", "russian": "вид, сортировать", "section": 1, "subsection": 2 },
    { "english": "sound", "russian": "звук", "section": 1, "subsection": 2 },
    { "english": "soup", "russian": "суп", "section": 1, "subsection": 2 },
    { "english": "south", "russian": "юг", "section": 2, "subsection": 0 },
    { "english": "space", "russian": "пространство, космос", "section": 1, "subsection": 2 },
    { "english": "spade", "russian": "лопата", "section": 1, "subsection": 1 },
    { "english": "special", "russian": "специальный", "section": 3, "subsection": 2 },
    { "english": "sponge", "russian": "губка", "section": 1, "subsection": 1 },
    { "english": "spoon", "russian": "ложка", "section": 1, "subsection": 1 },
    { "english": "spring", "russian": "весна", "section": 1, "subsection": 1 },
    { "english": "square", "russian": "квадрат", "section": 1, "subsection": 1 },
    { "english": "stage", "russian": "стадия, сцена, организовывать", "section": 1, "subsection": 2 },
    { "english": "stamp", "russian": "печать, марка, отпечатывать", "section": 1, "subsection": 1 },
    { "english": "star", "russian": "звезда", "section": 1, "subsection": 1 },
    { "english": "start", "russian": "начинать", "section": 1, "subsection": 2 },
    { "english": "statement", "russian": "утверждение", "section": 1, "subsection": 2 },
    { "english": "station", "russian": "станция", "section": 1, "subsection": 1 },
    { "english": "steam", "russian": "пар, париться, двигаться", "section": 1, "subsection": 2 },
    { "english": "steel", "russian": "сталь", "section": 1, "subsection": 2 },
    { "english": "stem", "russian": "стебель, происходить", "section": 1, "subsection": 1 },
    { "english": "step", "russian": "шаг, шагать", "section": 1, "subsection": 2 },
    { "english": "stick", "russian": "палка, прикреплять", "section": 1, "subsection": 1 },
    { "english": "sticky", "russian": "липкий", "section": 3, "subsection": 1 },
    { "english": "stiff", "russian": "жесткий", "section": 3, "subsection": 1 },
    { "english": "still", "russian": "все еще", "section": 2, "subsection": 0 },
    { "english": "stitch", "russian": "стежок, сшивать", "section": 1, "subsection": 2 },
    { "english": "stocking", "russian": "снабжать", "section": 1, "subsection": 1 },
    { "english": "stomach", "russian": "живот, смелость, переваривать", "section": 1, "subsection": 1 },
    { "english": "stone", "russian": "камень", "section": 1, "subsection": 2 },
    { "english": "stop", "russian": "останавливаться, остановка", "section": 1, "subsection": 2 },
    { "english": "store", "russian": "магазин, запас", "section": 1, "subsection": 1 },
    { "english": "story", "russian": "история", "section": 1, "subsection": 2 },
    { "english": "straight", "russian": "прямой", "section": 3, "subsection": 1 },
    { "english": "strange", "russian": "странный", "section": 3, "subsection": 2 },
    { "english": "street", "russian": "улица", "section": 1, "subsection": 1 },
    { "english": "stretch", "russian": "отрезки, протягивать, простираться", "section": 1, "subsection": 2 },
    { "english": "strong", "russian": "сильный", "section": 3, "subsection": 1 },
    { "english": "structure", "russian": "структура", "section": 1, "subsection": 2 },
    { "english": "substance", "russian": "вещество, сущность", "section": 1, "subsection": 2 },
    { "english": "such", "russian": "такой, таким образом", "section": 2, "subsection": 0 },
    { "english": "sudden", "russian": "внезапный", "section": 3, "subsection": 1 },
    { "english": "sugar", "russian": "сахар", "section": 1, "subsection": 2 },
    { "english": "suggestion", "russian": "предложение, предположение", "section": 1, "subsection": 2 },
    { "english": "summer", "russian": "лето", "section": 1, "subsection": 2 },
    { "english": "sun", "russian": "солнце", "section": 1, "subsection": 1 },
    { "english": "support", "russian": "поддержка, поддерживать", "section": 1, "subsection": 2 },
    { "english": "surprise", "russian": "сюрприз", "section": 1, "subsection": 2 },
    { "english": "sweet", "russian": "сладкий", "section": 3, "subsection": 1 },
    { "english": "swim", "russian": "плаванье, плавать", "section": 1, "subsection": 2 },
    { "english": "system", "russian": "система", "section": 1, "subsection": 2 },
    { "english": "table", "russian": "стол", "section": 1, "subsection": 1 },
    { "english": "tail", "russian": "хвост, выслеживать", "section": 1, "subsection": 1 },
    { "english": "take", "russian": "брать/взять", "section": 2, "subsection": 0 },
    { "english": "talk", "russian": "разговор, говорить", "section": 1, "subsection": 2 },
    { "english": "tall", "russian": "высокий", "section": 3, "subsection": 1 },
    { "english": "taste", "russian": "вкус, испытывать", "section": 1, "subsection": 2 },
    { "english": "tax", "russian": "налог, облагать налогом", "section": 1, "subsection": 2 },
    { "english": "teaching", "russian": "обучение", "section": 1, "subsection": 2 },
    { "english": "tendency", "russian": "тенденция", "section": 1, "subsection": 2 },
    { "english": "test", "russian": "проверять, тест", "section": 1, "subsection": 2 },
    { "english": "than", "russian": "чем", "section": 2, "subsection": 0 },
    { "english": "that", "russian": "что", "section": 2, "subsection": 0 },
    { "english": "the", "russian": "определенный", "section": 2, "subsection": 0 },
    { "english": "then", "russian": "тогда", "section": 2, "subsection": 0 },
    { "english": "theory", "russian": "теория", "section": 1, "subsection": 2 },
    { "english": "there", "russian": "там, туда", "section": 2, "subsection": 0 },
    { "english": "thick", "russian": "толстый, густой", "section": 3, "subsection": 1 },
    { "english": "thin", "russian": "худой, тонкий, жидкий", "section": 3, "subsection": 2 },
    { "english": "thing", "russian": "вещь", "section": 1, "subsection": 2 },
    { "english": "this", "russian": "это, этот", "section": 2, "subsection": 0 },
    { "english": "though", "russian": "хотя", "section": 2, "subsection": 0 },
    { "english": "thought", "russian": "мысль", "section": 1, "subsection": 2 },
    { "english": "thread", "russian": "нить, пронизывать", "section": 1, "subsection": 1 },
    { "english": "throat", "russian": "горло", "section": 1, "subsection": 1 },
    { "english": "through", "russian": "через", "section": 2, "subsection": 0 },
    { "english": "thumb", "russian": "листать, большой палец", "section": 1, "subsection": 1 },
    { "english": "thunder", "russian": "гром, греметь", "section": 1, "subsection": 2 },
    { "english": "ticket", "russian": "билет", "section": 1, "subsection": 1 },
    { "english": "tight", "russian": "трудный", "section": 3, "subsection": 1 },
    { "english": "till", "russian": "пока, до", "section": 2, "subsection": 0 },
    { "english": "time", "russian": "время", "section": 1, "subsection": 2 },
    { "english": "tin", "russian": "олово, консервная банка", "section": 1, "subsection": 2 },
    { "english": "tired", "russian": "усталый", "section": 3, "subsection": 1 },
    { "english": "to", "russian": "к, до, в", "section": 2, "subsection": 0 },
    { "english": "toe", "russian": "палец ноги", "section": 1, "subsection": 1 },
    { "english": "together", "russian": "вместе", "section": 2, "subsection": 0 },
    { "english": "tomorrow", "russian": "завтра", "section": 2, "subsection": 0 },
    { "english": "tongue", "russian": "язык", "section": 1, "subsection": 1 },
    { "english": "tooth", "russian": "зуб", "section": 1, "subsection": 1 },
    { "english": "top", "russian": "возглавлять, вершина, главный", "section": 1, "subsection": 2 },
    { "english": "touch", "russian": "прикосновение, касаться", "section": 1, "subsection": 2 },
    { "english": "town", "russian": "город", "section": 1, "subsection": 1 },
    { "english": "trade", "russian": "торговля, обменивать", "section": 1, "subsection": 2 },
    { "english": "train", "russian": "поезд", "section": 1, "subsection": 1 },
    { "english": "transport", "russian": "транспорт, транспортировать", "section": 1, "subsection": 2 },
    { "english": "tray", "russian": "поднос", "section": 1, "subsection": 1 },
    { "english": "tree", "russian": "дерево", "section": 1, "subsection": 1 },
    { "english": "trick", "russian": "уловка, обманывать", "section": 1, "subsection": 2 },
    { "english": "trouble", "russian": "проблема, беспокоить", "section": 1, "subsection": 2 },
    { "english": "trousers", "russian": "брюки", "section": 1, "subsection": 1 },
    { "english": "true", "russian": "правда, правдивый", "section": 3, "subsection": 1 },
    { "english": "turn", "russian": "поворот, поворачивать", "section": 1, "subsection": 2 },
    { "english": "twist", "russian": "завихрение, крутить", "section": 1, "subsection": 2 },
    { "english": "umbrella", "russian": "зонт", "section": 1, "subsection": 1 },
    { "english": "under", "russian": "под", "section": 2, "subsection": 0 },
    { "english": "unit", "russian": "единица", "section": 1, "subsection": 2 },
    { "english": "up", "russian": "вверх", "section": 2, "subsection": 0 },
    { "english": "use", "russian": "использование, использовать", "section": 1, "subsection": 2 },
    { "english": "value", "russian": "ценность, оценивать", "section": 1, "subsection": 2 },
    { "english": "verse", "russian": "стих", "section": 1, "subsection": 2 },
    { "english": "very", "russian": "очень", "section": 2, "subsection": 0 },
    { "english": "vessel", "russian": "судно, сосуд", "section": 1, "subsection": 2 },
    { "english": "view", "russian": "вид, взгляд, рассматривать", "section": 1, "subsection": 2 },
    { "english": "violent", "russian": "сильный, жестокий", "section": 3, "subsection": 1 },
    { "english": "voice", "russian": "голос, высказывать", "section": 1, "subsection": 2 },
    { "english": "waiting", "russian": "ожидание", "section": 3, "subsection": 1 },
    { "english": "walk", "russian": "ходьба, идти", "section": 1, "subsection": 2 },
    { "english": "wall", "russian": "стена", "section": 1, "subsection": 1 },
    { "english": "war", "russian": "война", "section": 1, "subsection": 2 },
    { "english": "warm", "russian": "теплый, нагревать", "section": 3, "subsection": 1 },
    { "english": "wash", "russian": "мытьё, стирать, чистить", "section": 1, "subsection": 2 },
    { "english": "waste", "russian": "ненужный, отходы, трата", "section": 1, "subsection": 2 },
    { "english": "watch", "russian": "часы", "section": 1, "subsection": 1 },
    { "english": "water", "russian": "вода", "section": 1, "subsection": 2 },
    { "english": "wave", "russian": "волна", "section": 1, "subsection": 2 },
    { "english": "wax", "russian": "воск, натирать воском", "section": 1, "subsection": 2 },
    { "english": "way", "russian": "путь", "section": 1, "subsection": 2 },
    { "english": "weather", "russian": "погода", "section": 1, "subsection": 2 },
    { "english": "week", "russian": "неделя", "section": 1, "subsection": 2 },
    { "english": "weight", "russian": "вес, нагружать", "section": 1, "subsection": 2 },
    { "english": "well", "russian": "хорошо, намного", "section": 2, "subsection": 0 },
    { "english": "west", "russian": "запад", "section": 2, "subsection": 0 },
    { "english": "wet", "russian": "влажный", "section": 3, "subsection": 1 },
    { "english": "wheel", "russian": "колесо, вертеть", "section": 1, "subsection": 1 },
    { "english": "when", "russian": "когда", "section": 2, "subsection": 0 },
    { "english": "where", "russian": "где, куда, откуда", "section": 2, "subsection": 0 },
    { "english": "while", "russian": "в то время как", "section": 2, "subsection": 0 },
    { "english": "whip", "russian": "кнут, хлестать", "section": 1, "subsection": 1 },
    { "english": "whistle", "russian": "свист, свистеть", "section": 1, "subsection": 1 },
    { "english": "white", "russian": "белый", "section": 3, "subsection": 2 },
    { "english": "who", "russian": "кто", "section": 2, "subsection": 0 },
    { "english": "why", "russian": "почему", "section": 2, "subsection": 0 },
    { "english": "wide", "russian": "широкий", "section": 3, "subsection": 1 },
    { "english": "will", "russian": "быть хотеть", "section": 2, "subsection": 0 },
    { "english": "wind", "russian": "ветер", "section": 1, "subsection": 2 },
    { "english": "window", "russian": "окно", "section": 1, "subsection": 1 },
    { "english": "wine", "russian": "вино", "section": 1, "subsection": 2 },
    { "english": "wing", "russian": "крыло", "section": 1, "subsection": 1 },
    { "english": "winter", "russian": "зима, зимовать", "section": 1, "subsection": 2 },
    { "english": "wire", "russian": "провод", "section": 1, "subsection": 1 },
    { "english": "wise", "russian": "мудрый", "section": 3, "subsection": 1 },
    { "english": "with", "russian": "с", "section": 2, "subsection": 0 },
    { "english": "woman", "russian": "женщина", "section": 1, "subsection": 2 },
    { "english": "wood", "russian": "лес", "section": 1, "subsection": 2 },
    { "english": "wool", "russian": "шерсть", "section": 1, "subsection": 2 },
    { "english": "word", "russian": "слово", "section": 1, "subsection": 2 },
    { "english": "work", "russian": "работа, работать", "section": 1, "subsection": 2 },
    { "english": "worm", "russian": "червь", "section": 1, "subsection": 1 },
    { "english": "wound", "russian": "проветривать, рана, ранить", "section": 1, "subsection": 2 },
    { "english": "writing", "russian": "письмо", "section": 1, "subsection": 2 },
    { "english": "wrong", "russian": "неправильный, несправедливость", "section": 3, "subsection": 2 },
    { "english": "year", "russian": "год", "section": 1, "subsection": 2 },
    { "english": "yellow", "russian": "жёлтый", "section": 3, "subsection": 1 },
    { "english": "yes", "russian": "да", "section": 2, "subsection": 0 },
    { "english": "yesterday", "russian": "вчера", "section": 2, "subsection": 0 },
    { "english": "you", "russian": "ты, вы", "section": 2, "subsection": 0 },
    { "english": "young", "russian": "молодой", "section": 3, "subsection": 1 }
]
